# Generated by Django 4.1 on 2022-10-25 19:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customer', '0001_initial'),
        ('team', '0004_alter_team_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_number', models.IntegerField(default=1)),
                ('customer_name', models.CharField(max_length=255)),
                ('customer_email', models.CharField(max_length=255)),
                ('customer_org_number', models.CharField(blank=True, max_length=255, null=True)),
                ('customer_address1', models.CharField(blank=True, max_length=255, null=True)),
                ('customer_address2', models.CharField(blank=True, max_length=255, null=True)),
                ('customer_zipcode', models.CharField(blank=True, max_length=255, null=True)),
                ('customer_place', models.CharField(blank=True, max_length=255, null=True)),
                ('customer_country', models.CharField(blank=True, max_length=255, null=True)),
                ('customer_contact_person', models.CharField(blank=True, max_length=255, null=True)),
                ('customer_contact_reference', models.CharField(blank=True, max_length=255, null=True)),
                ('sender_reference', models.CharField(blank=True, max_length=255, null=True)),
                ('receipt_type', models.CharField(choices=[('receipt', 'receipt'), ('credit_note', 'Credit note')], default='receipt', max_length=20)),
                ('due_days', models.IntegerField(default=14)),
                ('is_credited', models.BooleanField(default=False)),
                ('is_sent', models.BooleanField(default=False)),
                ('is_paid', models.BooleanField(default=False)),
                ('bankaccount', models.CharField(blank=True, max_length=266, null=True)),
                ('gross_amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('vat_amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('net_amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('discount_amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_receipts', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='customer.customer')),
                ('is_credit_for', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='receipt.receipt')),
                ('modified_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modified_receipts', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='team.team')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('quantity', models.IntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('net_amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('vat_rate', models.IntegerField(default=0)),
                ('discount', models.IntegerField(default=0)),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='receipt.receipt')),
            ],
        ),
    ]
