# Generated by Django 4.1 on 2022-11-11 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('INHOUSE', 'Inhouse'), ('EXTERNAL', 'External')], default='INHOUSE', max_length=15)),
                ('contributor_name', models.CharField(default='', max_length=100)),
                ('contributor_org', models.CharField(default='', max_length=100)),
                ('date_received', models.DateField(default='')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Funding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('contributor_name', models.CharField(default='', max_length=100)),
                ('contributor_org', models.CharField(default='', max_length=100)),
                ('date_received', models.DateField(default='')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OpeningBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opening_date', models.DateField(default='')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
            ],
        ),
    ]
