# Generated by Django 4.1 on 2022-10-31 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0008_remove_item_get_gross_amount'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Item',
            new_name='ExpenseItem',
        ),
    ]
